from django.conf.urls import patterns

urlpatterns = patterns('lorepo.course.views',
    (r'^list/(?P<project_id>\d+)/{0,1}$', 'courses_list'),
    (r'^get_publication_lessons/(?P<publication_id>\d+)/{0,1}', 'get_publication_lessons'),
    (r'^get_kids/(?P<publication_id>\d+)$', 'get_kids'),
    (r'^get_space/(?P<course_id>\d+)/(?P<space_id>\d+)$', 'get_space'),
    (r'^edit_table_of_contents/(?P<course_id>\d+)/(?P<project_id>\d+)/{0,1}', 'edit_table_of_contents'),
    (r'^save_table_of_contents/(?P<course_id>\d+)/{0,1}', 'save_table_of_contents'),
    (r'^rename/(?P<course_id>\d+)', 'rename'),
    (r'^remove/(?P<course_id>\d+)', 'remove'),
    (r'^remove_chapter/(?P<chapter_id>\d+)/(?P<course_id>\d+)', 'remove_chapter'),
    (r'^add_lesson/(?P<chapter_id>\d+)/(?P<course_id>\d+)', 'add_lesson'),
    (r'^add_lesson/eBook/(?P<course_id>\d+)$', 'add_lesson_to_eBook'),
    (r'^remove_lessons/(?P<course_id>\d+)$', 'remove_lessons'),
    (r'^export/(?P<course_id>\d+)$', 'trigger_export'),
    (r'^export/(?P<course_id>\d+)/async/(?P<user_id>\d+)/(?P<version>\d+)/(?P<include_player>\d+)$', 'export'),
    (r'^export_structure/(?P<course_id>\d+)/(?P<exported_course_id>\d+)/(?P<user_id>\d+)/(?P<version>\d+)$', 'export_structure'),
    (r'^export_lesson/(?P<content_id>\d+)/(?P<user_id>\d+)/(?P<exported_course_id>\d+)/(?P<version>\d+)/(?P<include_player>\d+)$', 'export_lesson'),
    (r'^set_structure_state$', 'set_structure_state'),
    (r'^save_resources', 'save_resources'),
    (r'^edit_resources/(?P<course_id>\d+)/(?P<content_id>\d+)$', 'edit_resources'),
    (r'^edit_resources_iframe/(?P<content_id>\d+)$', 'edit_resources_iframe'),
    (r'^get_resources/(?P<course_id>\d+)/(?P<content_id>\d+)/(?P<page_index>\d+)$', 'get_resources'),
)