MODULES_LIST = [
    "Check Button",
    "Check Counter",
    "Choice",
    "ErrorCounter",
    "Image",
    "Image gap",
    "Image source",
    "Lesson Reset",
    "Limited Check",
    "Limited Reset",
    "Ordering",
    "Page Progress",
    "Report",
    "Shape",
    "Source list",
    "Text",
    "nextPageButton",
    "prevPageButton",
    "resetButton",
    "cancelButton",
    "popupButton",
    "gotoPageButton"
]