#application: mauthor-dev
#version: 1276
runtime: python310
api_version: 1
threadsafe: false

instance_class: F2
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 32ms

builtins:
- remote_api: 'on'
# - appstats: on # uncomment to enable http://localhost:8000/_ah/stats

libraries:
- name: lxml
  version: "2.3"

inbound_services:
- warmup

handlers:
- url: /_ah/bounce
  script: wsgi.application
  login: admin

- url: /_ah/(mapreduce|queue|warmup|internalupload).*
  script: wsgi.application
  login: admin

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /media/images/(.*)
  static_files: lorepo/templates/static_files/images/\1
  upload: lorepo/templates/static_files/images/(.*)
  expiration: "7d"

- url: /media/content/(.*)
  static_files: lorepo/templates/static_files/content/\1
  upload: lorepo/templates/static_files/content/(.*)
  expiration: "7d"

- url: /media/style/fonts/(.*\.eot)
  static_files: lorepo/templates/static_files/style/fonts/\1
  upload: lorepo/templates/static_files/style/fonts/(.*\.eot)
  expiration: "30d"
  mime_type: font/eot

- url: /media/style/fonts/(.*\.woff)
  static_files: lorepo/templates/static_files/style/fonts/\1
  upload: lorepo/templates/static_files/style/fonts/(.*\.woff)
  expiration: "30d"
  mime_type: font/woff

- url: /media/style/fonts/(.*\.ttf)
  static_files: lorepo/templates/static_files/style/fonts/\1
  upload: lorepo/templates/static_files/style/fonts/(.*\.ttf)
  expiration: "30d"
  mime_type: font/ttf

- url: /media/style/fonts/(.*)
  static_files: lorepo/templates/static_files/style/fonts/\1
  upload: lorepo/templates/static_files/style/fonts/(.*)
  expiration: "30d"

- url: /media/icplayer/icplayer.nocache.js
  static_files: lorepo/templates/static_files/icplayer/icplayer.nocache.js
  upload: lorepo/templates/static_files/icplayer/icplayer.nocache.js
  expiration: '0'

- url: /media/iceditor/iceditor.nocache.js
  static_files: lorepo/templates/static_files/iceditor/iceditor.nocache.js
  upload: lorepo/templates/static_files/iceditor/iceditor.nocache.js
  expiration: '0'

- url: /media/addoneditor/addoneditor.nocache.js
  static_files: lorepo/templates/static_files/addoneditor/addoneditor.nocache.js
  upload: lorepo/templates/static_files/addoneditor/addoneditor.nocache.js
  expiration: '0'

- url: /media/styles.css
  static_files: lorepo/templates/static_files/styles.css
  upload: lorepo/templates/static_files/styles.css
  expiration: '0'

- url: /media/frontend/build/1120
  static_dir: mauthor/templates/static_files/frontend
  expiration: "7d"
  secure: always

- url: /media/apidoc/$
  static_files: lorepo/templates/static_files/apidoc/index.html
  upload: lorepo/templates/static_files/apidoc/index.html
  login: admin

- url: /media/apidoc
  static_dir: lorepo/templates/static_files/apidoc/
  login: admin

- url: /media
  static_dir: lorepo/templates/static_files

- url: (^/mycontent/copy_public_lesson/(\d+)$)
  script: wsgi.application

- url: (^/mycontent/(\d+)/editor$)|(^/mycontent/(\d+)/exit_editor$)|(^/mycontent/(\d+)/changeicon$)|(^/mycontent/(\d+)/metadata$)|(^/mycontent/(\d+)/pagemetadata$)|(^/mycontent/(\d+)/cancelediting$)|(^/mycontent/addon/(\d+)$)|(^/mycontent/(\d+)/setversion/(\d+)$)|(^/mycontent/(\w+)/getaddon$)
  script: wsgi.application
  secure: always

- url: (^/mycontent/(\d+)/editaddon$)|(^/mycontent/view_addon/(\d+)$)|(^/mycontent/(\d+)/removeversion/(\d+)/(\d+)$)|(^/mycontent/copy/(\d+)$)|(^/mycontent/copy/(\d+)/(\d+)$)|(^/states/show_kanban/(\d+))
  script: wsgi.application
  secure: always

- url: (^/mycontent/(\d+)/confirm_self_editing_addon$)|(^/mycontent/(\d+)/confirm_self_editing$)|(^/mycontent/(\d+)/removeversion/(\d+)$)|(^/mycontent/(\d+)/confirm_editing$)
  script: wsgi.application
  secure: always

- url: (^/?$)|(^/home(/(.*))?$)|(^/accounts/login/?$)|(^/corporate/?$)|(^/mycontent/view/(\d+)$)|(^/corporate/view/(\d+)$)|(^/dashboard/?$)|(^/accounts/register/?$)|(^/accounts/register/finish$)|(^/mycontent/?$)|(^/mycontent(/(.*))?$)|(^/panel(/(.*))?$)|(^/corporate/list/(\d+)$)|(^/corporate/interactive-tutorials$)|(^/mycontent/addcontent/(\d+)$)|(^/corporate/list/(\d+)/trash$)
  static_files: mauthor/templates/static_files/frontend/dist/index.html
  upload: mauthor/templates/static_files/frontend/dist/index.html
  expiration: "0"
  secure: always

- url: /mauthor_media
  static_dir: src/muthor/templates/static_files

- url: /favicon\.ico
  static_files: lorepo/templates/static_files/favicon.ico
  upload: lorepo/templates/static_files/favicon\.ico
  expiration: "7d"
  
- url: /robots\.txt
  static_files: lorepo/templates/static_files/robots.txt
  upload: lorepo/templates/static_files/robots\.txt

- url: /user/loginas/(.*)
  script: wsgi.application
  login: admin

- url: /.*
  script: wsgi.application

skip_files:
  - manage.py
  - README.md
  - install_deps
  - requirements.txt
  - sitepackages/google_appengine*
  - \.storage.*
  - \.git
  - (.*)\.pyc
  - templates/static_files/frontend/node_modules
  - templates/static_files/frontend/bower_components
  - templates/static_files/frontend/typings
  - templates/static_files/frontend/app  - templates/static_files/frontend/node_modules
  - templates/static_files/frontend/bower_components
  - templates/static_files/frontend/typings
  - templates/static_files/frontend/app  - templates/static_files/frontend/node_modules
  - templates/static_files/frontend/bower_components
  - templates/static_files/frontend/typings
  - templates/static_files/frontend/app